import {
  PageItem,
  ServiceItem,
  ProductCategory,
  ProductItem,
  ProjectItem,
  SiteSettings,
  NavigationItem,
  FooterSection,
  MediaItem,
} from '../types';
import { LIBRAIRIE_CATALOGUE_URL } from './constants';
export const INITIAL_SETTINGS: SiteSettings = {
  company_name: 'HINOV Group',
  tagline: 'Prestation de services & Solutions intégrées',
  phone: '+225 07 19 54 95 82',
  email: 'hinovgroup@hinovgroup.com',
  address: 'Yopougon, Cité Verte',
  city: 'Abidjan',
  country: "Côte d'Ivoire",
  whatsapp: '+2250719549582',
  whatsapp_enabled: true,
  logo_url: '/assets/icon-512.png',
  favicon_url: '/assets/icon-512.png',
  facebook_url: '',
  instagram_url: '',
  linkedin_url: '',
  tiktok_url: '',
  default_seo_title: 'HINOV Group — Prestation de services & Solutions intégrées',
  default_seo_description:
    'Site officiel HINOV Group : Informatique, Imprimerie, Développement logiciel, Câblage réseau, Librairie & Papeterie.',
  quote_notification_email: 'hinovgroup@hinovgroup.com',
};

export const INITIAL_MEDIA: MediaItem[] = [
  {
    id: 'med-logo-512',
    filename: 'icon-512.png',
    url: '/assets/icon-512.png',
    mime_type: 'image/png',
    file_size: 156533,
    width: 512,
    height: 512,
    alt_text: 'Logo officiel et icône de marque HINOV Group',
    title: 'Logo officiel HINOV (icon-512.png)',
    category: 'Identité',
    folder: 'Identité',
    created_at: '2026-09-08T13:00:00Z',
    used_in: [{ type: 'page', name: 'Global', location: 'Logo principal & Favicon' }],
  },
  {
    id: 'med-hero-1',
    filename: 'hinov-hero-presentation.jpg',
    url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80',
    mime_type: 'image/jpeg',
    file_size: 245000,
    width: 1600,
    height: 900,
    alt_text: 'Équipe HINOV Group collaborant en réunion technique',
    title: 'HINOV Group Synergie',
    category: 'Accueil',
    created_at: '2026-09-08T10:00:00Z',
    used_in: [{ type: 'page', name: 'Accueil', location: 'Hero' }],
  },
  {
    id: 'med-serv-info',
    filename: 'service-informatique.jpg',
    url: 'https://images.unsplash.com/photo-1597733336794-12d05021d510?auto=format&fit=crop&w=1200&q=80',
    mime_type: 'image/jpeg',
    file_size: 198000,
    width: 1200,
    height: 800,
    alt_text: 'Maintenance informatique et matériel',
    title: 'Informatique & Systèmes',
    category: 'Services',
    created_at: '2026-09-08T10:00:00Z',
    used_in: [{ type: 'service', name: 'Informatique', location: 'Image principale' }],
  },
  {
    id: 'med-serv-print',
    filename: 'service-imprimerie.jpg',
    url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    mime_type: 'image/jpeg',
    file_size: 215000,
    width: 1200,
    height: 800,
    alt_text: 'Impression professionnelle et sérigraphie',
    title: 'Imprimerie & Graphisme',
    category: 'Services',
    created_at: '2026-09-08T10:00:00Z',
    used_in: [{ type: 'service', name: 'Imprimerie', location: 'Image principale' }],
  },
  {
    id: 'med-serv-dev',
    filename: 'service-developpement.jpg',
    url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    mime_type: 'image/jpeg',
    file_size: 210000,
    width: 1200,
    height: 800,
    alt_text: 'Conception et programmation de solutions logicielles',
    title: 'Développement de logiciels',
    category: 'Services',
    created_at: '2026-09-08T10:00:00Z',
    used_in: [{ type: 'service', name: 'Développement de logiciels', location: 'Image principale' }],
  },
  {
    id: 'med-serv-network',
    filename: 'service-cablage-reseau.jpg',
    url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80',
    mime_type: 'image/jpeg',
    file_size: 230000,
    width: 1200,
    height: 800,
    alt_text: 'Infrastructures et câblage réseau informatique',
    title: 'Câblage réseau & Baie de brassage',
    category: 'Services',
    created_at: '2026-09-08T10:00:00Z',
    used_in: [{ type: 'service', name: 'Câblage réseau et informatique', location: 'Image principale' }],
  },
  {
    id: 'med-serv-stationery',
    filename: 'service-papeterie.jpg',
    url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=1200&q=80',
    mime_type: 'image/jpeg',
    file_size: 185000,
    width: 1200,
    height: 800,
    alt_text: 'Fournitures scolaires et accessoires de papeterie',
    title: 'Librairie & Papeterie HINOV',
    category: 'Services',
    created_at: '2026-09-08T10:00:00Z',
    used_in: [{ type: 'service', name: 'Librairie & papeterie', location: 'Image principale' }],
  },
  {
    id: 'med-vid-dev',
    filename: 'hinov-tech-software-loop.mp4',
    file_name: 'hinov-tech-software-loop.mp4',
    url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
    mime_type: 'video/mp4',
    media_type: 'video',
    file_size: 4800000,
    duration: 15,
    poster_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    alt_text: 'Développement de logiciels et programmation chez HINOV Group',
    title: 'Développement & Solutions Logicielles (Vidéo courte)',
    category: 'Vidéos',
    folder: 'Services',
    created_at: '2026-09-08T10:00:00Z',
    used_in: [{ type: 'page', name: 'Accueil', location: 'Section Démo Vidéo' }],
  },
  {
    id: 'med-vid-office',
    filename: 'hinov-bureautique-informatique.mp4',
    file_name: 'hinov-bureautique-informatique.mp4',
    url: 'https://vjs.zencdn.net/v/oceans.mp4',
    mime_type: 'video/mp4',
    media_type: 'video',
    file_size: 3600000,
    duration: 12,
    poster_url: 'https://images.unsplash.com/photo-1597733336794-12d05021d510?auto=format&fit=crop&w=1200&q=80',
    alt_text: 'Poste de travail et environnement informatique HINOV Group',
    title: 'Bureautique & Ingénierie Informatique (Vidéo courte)',
    category: 'Vidéos',
    folder: 'Services',
    created_at: '2026-09-08T10:00:00Z',
    used_in: [],
  },
  {
    id: 'med-vid-demo',
    filename: 'hinov-presentation-video.mp4',
    file_name: 'hinov-presentation-video.mp4',
    url: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
    mime_type: 'video/mp4',
    media_type: 'video',
    file_size: 5200000,
    duration: 15,
    poster_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80',
    alt_text: 'Démonstration dynamique des infrastructures HINOV Group',
    title: 'Immersion & Déploiement HINOV (Vidéo courte)',
    category: 'Vidéos',
    folder: 'Général',
    created_at: '2026-09-08T10:00:00Z',
    used_in: [],
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'serv-1',
    name: 'Informatique',
    slug: 'informatique',
    short_description:
      'Maintenance de systèmes et réseaux informatiques, vente de matériels informatiques, installation de box Wi-Fi et caméras de surveillance.',
    description:
      "HINOV Group assure une prise en charge complète de votre parc informatique. Nos techniciens interviennent pour la maintenance préventive et corrective de vos postes et serveurs, l'équipement en matériel de haute performance, le déploiement de connexions Wi-Fi optimisées ainsi que l'installation de caméras de sécurité pour particuliers et professionnels.",
    icon_name: 'Monitor',
    accent_color: 'blue',
    featured_image_url:
      'https://images.unsplash.com/photo-1597733336794-12d05021d510?auto=format&fit=crop&w=1200&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1597733336794-12d05021d510?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1200&q=80',
    ],
    prestations: [
      'Maintenance de système et réseau informatique',
      'Vente de matériels informatiques',
      'Installation de box Wi-Fi',
      'Installation de caméra',
    ],
    advantages: [
      'Diagnostic technique approfondi',
      'Intervention rapide sur site et à distance',
      'Matériel professionnel certifié et garanti',
      'Accompagnement et conseils personnalisés',
    ],
    status: 'published',
    sort_order: 1,
    seo_title: 'Service Informatique — HINOV Group',
    seo_description:
      'Maintenance système & réseau, vente de matériels, installation Wi-Fi et caméras de sécurité par HINOV Group.',
    created_at: '2026-09-08T10:00:00Z',
    updated_at: '2026-09-08T10:00:00Z',
  },
  {
    id: 'serv-2',
    name: 'Imprimerie',
    slug: 'imprimerie',
    short_description:
      'Impression tous supports, confection de flyers, catalogues, agendas, logos, cartes de visite, cartes de mariage et sérigraphie.',
    description:
      "Notre pôle imprimerie combine précision technique et créativité graphique pour donner vie à tous vos projets de communication visuelle. Du petit au très grand format, nous garantissons un rendu colorimétrique fidèle, des finitions soignées et le respect rigoureux de vos délais.",
    icon_name: 'Printer',
    accent_color: 'orange',
    featured_image_url:
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1200&q=80',
    ],
    prestations: [
      'Impression sur tout support',
      'Impression grand format',
      'Impression petit format',
      'Confection de flyers',
      'Confection de catalogues',
      'Confection d’agendas',
      'Impression de documents officiels',
      'Confection de logos',
      'Cartes de visite',
      'Cartes de mariage',
      'Sérigraphie',
    ],
    advantages: [
      'Qualité de tirage offset et numérique haute définition',
      'Large sélection de papiers et supports spéciaux',
      'Finitions sur mesure (pelliculage, vernis, gaufrage)',
      'Déclinaison graphique de votre identité de marque',
    ],
    status: 'published',
    sort_order: 2,
    seo_title: 'Imprimerie & Sérigraphie — HINOV Group',
    seo_description:
      'Impression tout support, grand format, flyers, catalogues, cartes de visite et sérigraphie par HINOV Group.',
    created_at: '2026-09-08T10:00:00Z',
    updated_at: '2026-09-08T10:00:00Z',
  },
  {
    id: 'serv-3',
    name: 'Développement de logiciels',
    slug: 'developpement-logiciel',
    short_description:
      'Conception, développement, tests, déploiement et maintenance d’applications informatiques sur mesure et évolutives.',
    description:
      "Le pôle développement logiciel d'HINOV Group conçoit des architectures logicielles pérennes adaptées à vos processus métiers. Nous prenons en charge chaque étape du cycle de vie logiciel : recueil des exigences, modélisation, sélection des briques technologiques, programmation robuste, tests de conformité, mise en production et support continu.",
    icon_name: 'Code2',
    accent_color: 'blue',
    featured_image_url:
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80',
    ],
    prestations: [
      'Analyse des besoins et spécifications fonctionnelles',
      'Choix des technologies adaptées aux objectifs',
      'Conception et programmation d’applications',
      'Tests d’intégration et validation rigoureuse',
      'Déploiement et mise en production sécurisée',
      'Correction des anomalies et veille applicative',
      'Amélioration continue et évolution fonctionnelle',
    ],
    advantages: [
      'Méthodologie agile et itérative',
      'Solutions sur-mesure alignées sur vos processus',
      'Sécurité et scalabilité intégrées dès la conception',
      'Documentation complète et formation des utilisateurs',
    ],
    status: 'published',
    sort_order: 3,
    seo_title: 'Développement de logiciels sur mesure — HINOV Group',
    seo_description:
      'Conception, programmation, déploiement et maintenance d’applications informatiques avec HINOV Group.',
    created_at: '2026-09-08T10:00:00Z',
    updated_at: '2026-09-08T10:00:00Z',
  },
  {
    id: 'serv-4',
    name: 'Câblage réseau et informatique',
    slug: 'cablage-reseau-informatique',
    short_description:
      'Conception, installation, configuration, mise en service et maintenance d’infrastructures de réseaux informatiques.',
    description:
      "Une connectivité fiable et structurée constitue la colonne vertébrale de toute organisation moderne. HINOV Group réalise des installations de câblage cuivre et optique, l'aménagement de baies de brassage, le paramétrage des commutateurs et routeurs, ainsi que la certification des liens réseaux pour entreprises, administrations, établissements scolaires et résidences de particuliers.",
    icon_name: 'Network',
    accent_color: 'green',
    featured_image_url:
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1520869562399-e772f142f422?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    ],
    prestations: [
      'Conception d’infrastructures de réseaux informatiques',
      'Installation et câblage structuré (cuivre & fibre)',
      'Configuration des commutateurs, routeurs et bornes',
      'Mise en service et certification de conformité',
      'Maintenance préventive et dépannage réseau',
      'Interventions adaptées : entreprises, administrations, écoles et particuliers',
    ],
    advantages: [
      'Respect strict des normes de câblage structuré',
      'Identification et étiquetage minutieux des liaisons',
      'Optimisation des flux de données et de la bande passante',
      'Pérénité des installations face aux évolutions futures',
    ],
    status: 'published',
    sort_order: 4,
    seo_title: 'Câblage réseau et informatique — HINOV Group',
    seo_description:
      'Conception, installation, configuration et maintenance de réseaux informatiques par HINOV Group.',
    created_at: '2026-09-08T10:00:00Z',
    updated_at: '2026-09-08T10:00:00Z',
  },
  {
    id: 'serv-5',
    name: 'Librairie & papeterie',
    slug: 'librairie-papeterie',
    short_description:
      'Fournitures scolaires, accessoires scolaires, gourdes, sacs, parapluies, imperméables et fournitures de bureau complètes.',
    description:
      "HINOV Group accompagne les familles, les élèves, les étudiants et les professionnels en proposant une gamme exhaustive d'articles de papeterie et de fournitures scolaires de qualité supérieure. Découvrez également notre sélection d'accessoires pratiques pour le quotidien : sacs ergonomiques, gourdes durables, parapluies et imperméables.",
    icon_name: 'BookOpen',
    accent_color: 'magenta',
    featured_image_url:
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=1200&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507842229496-c1184a2c1402?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=1200&q=80',
    ],
    prestations: [
      'Fournitures scolaires complètes pour tous cycles',
      'Accessoires scolaires pratiques et ergonomiques',
      'Gourdes isothermes et bouteilles réutilisables',
      'Sacs et cartables résistants',
      'Parapluies compacts et grands modèles',
      'Imperméables de protection',
      'Fournitures et consommables de bureau pour entreprises',
    ],
    advantages: [
      'Large disponibilité en stock toute l’année',
      'Matériaux résistants et adaptés à une utilisation intensive',
      'Tarifs compétitifs avec options de devis pour commandes groupées',
      'Conseils personnalisés selon vos listes de rentrée ou besoins d’entreprise',
    ],
    status: 'published',
    sort_order: 5,
    seo_title: 'Librairie & Papeterie — HINOV Group',
    seo_description:
      'Fournitures scolaires, accessoires, sacs, gourdes, parapluies et fournitures de bureau chez HINOV Group.',
    created_at: '2026-09-08T10:00:00Z',
    updated_at: '2026-09-08T10:00:00Z',
  },
];

export const INITIAL_CATEGORIES: ProductCategory[] = [
  {
    id: 'cat-1',
    name: 'Fournitures scolaires',
    slug: 'fournitures-scolaires',
    description: 'Cahiers, stylos, règles, classeurs et matériel pédagogique essentiel.',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'cat-2',
    name: 'Accessoires scolaires',
    slug: 'accessoires-scolaires',
    description: 'Gourdes, sacs, cartables, trousses et équipements de protection.',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'cat-3',
    name: 'Fournitures de bureau',
    slug: 'fournitures-de-bureau',
    description: 'Rames de papier, chemises, classeurs, stylos de bureau et consommables.',
    sort_order: 3,
    is_active: true,
  },
  {
    id: 'cat-4',
    name: 'Matériels informatiques',
    slug: 'materiels-informatiques',
    description: 'Périphériques, équipements réseaux, box Wi-Fi et caméras.',
    sort_order: 4,
    is_active: true,
  },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-1',
    category_id: 'cat-2',
    category_name: 'Accessoires scolaires',
    name: 'Gourde Isotherme Écolier Durable',
    slug: 'gourde-isotherme-ecolier-durable',
    reference: 'HNV-ACC-001',
    short_description: 'Gourde étanche en inox 500ml conservant le chaud et le froid.',
    description:
      "Conçue spécialement pour les écoliers et collégiens, cette gourde en acier inoxydable de qualité alimentaire est résistante aux chocs. Bouchon étanche sans BPA avec système d'ouverture sécurisé et anse de transport pratique.",
    price: 6500,
    currency: 'FCFA',
    unit: 'pièce',
    price_display_mode: 'show',
    availability: 'in_stock',
    is_featured: true,
    status: 'published',
    primary_image_url:
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Contenance', value: '500 ml' },
      { key: 'Matière', value: 'Inox 18/8 sans BPA' },
      { key: 'Isolation', value: 'Double paroi sous vide' },
    ],
    sort_order: 1,
    created_at: '2026-09-08T10:00:00Z',
    updated_at: '2026-09-08T10:00:00Z',
  },
  {
    id: 'prod-2',
    category_id: 'cat-2',
    category_name: 'Accessoires scolaires',
    name: 'Sac à Dos Scolaire Ergonomique Renforcé',
    slug: 'sac-a-dos-scolaire-ergonomique',
    reference: 'HNV-ACC-002',
    short_description: 'Sac à dos imperméable avec dos matelassé et bretelles ergonomiques.',
    description:
      'Sac à dos haute résistance conçu pour supporter le poids des manuels scolaires sans fatiguer le dos. Doté de multiples compartiments zippés, de poches latérales pour gourde et de bandes réfléchissantes de sécurité.',
    price: 18500,
    currency: 'FCFA',
    unit: 'pièce',
    price_display_mode: 'show',
    availability: 'in_stock',
    is_featured: true,
    status: 'published',
    primary_image_url:
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Volume', value: '25 Litres' },
      { key: 'Matière', value: 'Polyester 900D hydrofuge' },
      { key: 'Dos', value: 'Matelassé respirant' },
    ],
    sort_order: 2,
    created_at: '2026-09-08T10:00:00Z',
    updated_at: '2026-09-08T10:00:00Z',
  },
  {
    id: 'prod-3',
    category_id: 'cat-2',
    category_name: 'Accessoires scolaires',
    name: 'Parapluie Compact Coupe-Vent Haute Résistance',
    slug: 'parapluie-compact-coupe-vent',
    reference: 'HNV-ACC-003',
    short_description: 'Parapluie pliable renforcé à ouverture automatique rapide.',
    description:
      "Parapluie robuste avec armature en fibre de verre et toile haute densité déperlante. Idéal pour affronter les fortes averses en restant protégé.",
    price: 7000,
    currency: 'FCFA',
    unit: 'pièce',
    price_display_mode: 'show',
    availability: 'in_stock',
    is_featured: true,
    status: 'published',
    primary_image_url:
      'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?auto=format&fit=crop&w=800&q=80',
    sort_order: 3,
    created_at: '2026-09-08T10:00:00Z',
    updated_at: '2026-09-08T10:00:00Z',
  },
  {
    id: 'prod-4',
    category_id: 'cat-4',
    category_name: 'Matériels informatiques',
    name: 'Kit Box Wi-Fi Longue Portée Dual-Band',
    slug: 'kit-box-wifi-longue-portee',
    reference: 'HNV-IT-001',
    short_description: 'Routeur Wi-Fi Gigabit haute stabilité avec installation possible par nos techniciens.',
    description:
      'Équipement réseau performant garantissant une couverture Wi-Fi stable et fluide dans toute votre entreprise, établissement scolaire ou domicile.',
    price: 0,
    currency: 'FCFA',
    unit: 'kit',
    price_display_mode: 'on_demand',
    availability: 'in_stock',
    is_featured: true,
    status: 'published',
    primary_image_url:
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80',
    specifications: [
      { key: 'Débit', value: 'Jusqu’à 1200 Mbps' },
      { key: 'Antennes', value: '4 antennes directionnelles' },
      { key: 'Ports', value: '4 ports Gigabit Ethernet' },
    ],
    sort_order: 4,
    created_at: '2026-09-08T10:00:00Z',
    updated_at: '2026-09-08T10:00:00Z',
  },
];

export const INITIAL_PROJECTS: ProjectItem[] = [];

export const INITIAL_PAGES: PageItem[] = [
  {
    id: 'page-home',
    title: 'Accueil',
    slug: 'accueil',
    status: 'published',
    template: 'standard',
    seo_title: 'HINOV Group — Accueil & Solutions intégrées',
    seo_description:
      'Bienvenue chez HINOV Group : Informatique, Imprimerie, Développement logiciel, Câblage réseau & Librairie Papeterie à Abidjan, Côte d’Ivoire.',
    updated_at: '2026-09-08T10:00:00Z',
    created_at: '2026-09-08T10:00:00Z',
    sections: [
      {
        id: 'sec-hero',
        page_id: 'page-home',
        section_type: 'hero',
        title: "L'excellence au service de vos ambitions",
        subtitle: 'PRESTATION DE SERVICES & SOLUTIONS INTÉGRÉES',
        content:
          "HINOV Group est votre partenaire de confiance à Abidjan pour tous vos projets technologiques, imprimés et de fournitures. Nous allions rigueur technique, créativité et engagement pour garantir votre satisfaction.",
        image_url:
          'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1600&q=80',
        image_alt: 'Équipe HINOV Group au travail',
        cta_label: 'Demander un devis',
        cta_link: '/devis',
        secondary_cta_label: 'Découvrir nos services',
        secondary_cta_link: '/services',
        sort_order: 1,
        is_visible: true,
      },
      {
        id: 'sec-presentation',
        page_id: 'page-home',
        section_type: 'presentation',
        title: 'À propos de HINOV Group',
        subtitle: 'NOTRE ENGAGEMENT QUALITÉ',
        content:
          "Entreprise ivoirienne de prestation de services basée à Yopougon, HINOV Group met l'accent sur la qualité irréprochable des réalisations et la satisfaction intégrale des clients. Notre équipe multidisciplinaire apporte des réponses adaptées aux besoins des entreprises, administrations, établissements scolaires et particuliers.",
        image_url:
          'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1200&q=80',
        cta_label: 'En savoir plus sur nous',
        cta_link: '/a-propos',
        sort_order: 2,
        is_visible: true,
      },
      {
        id: 'sec-services',
        page_id: 'page-home',
        section_type: 'services_grid',
        title: 'Nos 5 domaines d’expertise',
        subtitle: 'SOLUTIONS COMPLÈTES & CLÉ EN MAIN',
        content:
          'Explorez nos domaines d’intervention officiels : Informatique, Imprimerie, Développement de logiciels, Câblage réseau et Librairie & papeterie.',
        cta_label: 'Tous nos services',
        cta_link: '/services',
        sort_order: 3,
        is_visible: true,
      },
      {
        id: 'sec-video-spotlight',
        page_id: 'page-home',
        section_type: 'video_spotlight',
        title: 'L’ingénierie & le digital en action',
        subtitle: 'IMMERSION TECHNIQUE & DÉMONSTRATION',
        content:
          'De la maintenance d’infrastructures réseau complexes au développement sur-mesure de logiciels métiers, visualisez l’engagement et l’expertise technique des équipes HINOV Group.',
        media_type: 'video',
        video_url:
          'https://vjs.zencdn.net/v/oceans.mp4',
        video_poster_url:
          'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
        video_autoplay: true,
        video_loop: true,
        video_muted: true,
        video_controls: true,
        cta_label: 'Demander un devis',
        cta_link: '/devis',
        secondary_cta_label: 'Nos réalisations',
        secondary_cta_link: '/realisations',
        sort_order: 4,
        is_visible: true,
      },
      {
        id: 'sec-why-us',
        page_id: 'page-home',
        section_type: 'why_us',
        title: 'Pourquoi choisir HINOV Group ?',
        subtitle: 'DES ATOUTS CONCRETS',
        content:
          'Une approche globale et rigoureuse pour garantir la pérennité et le succès de chaque intervention.',
        sort_order: 5,
        is_visible: true,
      },
      {
        id: 'sec-featured-products',
        page_id: 'page-home',
        section_type: 'featured_products',
        title: 'Sélection du catalogue',
        subtitle: 'FOURNITURES & ÉQUIPEMENTS MIS EN AVANT',
        content:
          'Découvrez un aperçu de nos fournitures scolaires, articles de bureau et équipements informatiques disponibles sur commande ou devis.',
        cta_label: 'Voir tout le catalogue',
        cta_link: '/catalogue',
        sort_order: 5,
        is_visible: true,
      },
      {
        id: 'sec-projects',
        page_id: 'page-home',
        section_type: 'projects_grid',
        title: 'Nos Réalisations',
        subtitle: 'TRAVAUX & PROJETS CONCRETS',
        content:
          'Consultez nos réalisations certifiées dans l’impression, le câblage, le déploiement logiciel et la fourniture d’équipements.',
        cta_label: 'Voir toutes les réalisations',
        cta_link: '/realisations',
        sort_order: 6,
        is_visible: true,
      },
      {
        id: 'sec-cta',
        page_id: 'page-home',
        section_type: 'cta',
        title: 'Vous avez un projet ou un besoin spécifique ?',
        subtitle: 'DEVIS GRATUIT & RÉPONSE RAPIDE',
        content:
          'Notre équipe étudie gratuitement votre demande pour vous proposer une solution technique et financière adaptée à vos objectifs.',
        cta_label: 'Demander un devis en ligne',
        cta_link: '/devis',
        secondary_cta_label: 'Nous contacter directement',
        secondary_cta_link: '/contact',
        sort_order: 7,
        is_visible: true,
      },
      {
        id: 'sec-contact',
        page_id: 'page-home',
        section_type: 'contact_quick',
        title: 'Contactez HINOV Group',
        subtitle: 'NOUS SOMMES À VOTRE ÉCOUTE',
        content:
          'Basés à Yopougon, Cité Verte, nous sommes disponibles par téléphone, WhatsApp ou email pour répondre à toutes vos interrogations.',
        sort_order: 8,
        is_visible: true,
      },
    ],
  },
  {
    id: 'page-about',
    title: 'À propos',
    slug: 'a-propos',
    status: 'published',
    template: 'standard',
    seo_title: 'À propos — HINOV Group',
    seo_description:
      'Découvrez HINOV Group : notre mission, nos valeurs d’exigence et notre engagement constant pour la satisfaction client.',
    updated_at: '2026-09-08T10:00:00Z',
    created_at: '2026-09-08T10:00:00Z',
    sections: [
      {
        id: 'sec-about-hero',
        page_id: 'page-about',
        section_type: 'hero',
        title: 'À propos de HINOV Group',
        subtitle: 'PRESTATION DE SERVICES & EXCELLENCE',
        content:
          "HINOV Group est une entreprise de prestation de services résolument orientée vers la qualité des réalisations et la satisfaction de ses partenaires et clients.",
        image_url:
          'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1200&q=80',
        sort_order: 1,
        is_visible: true,
      },
      {
        id: 'sec-about-presentation',
        page_id: 'page-about',
        section_type: 'presentation',
        title: 'Qui sommes-nous ?',
        subtitle: 'UNE STRUCTURE DYNAMIQUE ET MULTIDISCIPLINAIRE',
        content:
          "Implantée à Yopougon (Cité Verte), HINOV Group intervient à la croisée des technologies numériques, des arts graphiques de l'imprimerie, des infrastructures réseaux et de la distribution d'articles scolaires et de bureau.\n\nNotre démarche repose sur l'écoute active des besoins réels de chaque client afin de délivrer des solutions tangibles, pérennes et compétitives.",
        sort_order: 2,
        is_visible: true,
      },
      {
        id: 'sec-about-values',
        page_id: 'page-about',
        section_type: 'why_us',
        title: 'Nos valeurs fondamentales',
        subtitle: 'CE QUI GUIDE NOS ACTIONS',
        content:
          "Qualité sans compromis, réactivité dans l'exécution, transparence relationnelle et accompagnement dans la durée.",
        sort_order: 3,
        is_visible: true,
      },
      {
        id: 'sec-about-cta',
        page_id: 'page-about',
        section_type: 'cta',
        title: 'Prêt à collaborer avec HINOV Group ?',
        subtitle: 'UN SEUL INTERLOCUTEUR POUR TOUS VOS BESOINS',
        content:
          'Discutons dès aujourd’hui de votre cahier des charges et recevez une proposition détaillée.',
        cta_label: 'Demander un devis',
        cta_link: '/devis',
        sort_order: 4,
        is_visible: true,
      },
    ],
  },
];

export const INITIAL_NAVIGATION: NavigationItem[] = [
  { id: 'nav-home', label: 'Accueil', path: '/', sort_order: 1, is_visible: true },
  { id: 'nav-about', label: 'À propos', path: '/a-propos', sort_order: 2, is_visible: true },
  {
    id: 'nav-services',
    label: 'Services',
    path: '/services',
    sort_order: 3,
    is_visible: true,
    children: [
      { label: 'Informatique', path: '/services/informatique' },
      { label: 'Imprimerie', path: '/services/imprimerie' },
      { label: 'Développement de logiciels', path: '/services/developpement-logiciel' },
      { label: 'Câblage réseau et informatique', path: '/services/cablage-reseau-informatique' },
      { label: 'Librairie & papeterie', path: '/services/librairie-papeterie' },
    ],
  },
  { id: 'nav-projects', label: 'Réalisations', path: '/realisations', sort_order: 4, is_visible: true },
  { id: 'nav-catalog', label: 'Catalogue', path: '/catalogue', sort_order: 5, is_visible: true },
  { id: 'nav-librairie-catalog', label: 'Catalogue Librairie', path: LIBRAIRIE_CATALOGUE_URL, sort_order: 6, is_visible: true },
  { id: 'nav-contact', label: 'Contact', path: '/contact', sort_order: 7, is_visible: true },
];

export const INITIAL_FOOTER: FooterSection[] = [
  {
    id: 'foot-services',
    title: 'Nos Services',
    sort_order: 1,
    is_visible: true,
    links: [
      { label: 'Informatique & Maintenance', path: '/services/informatique' },
      { label: 'Imprimerie & Sérigraphie', path: '/services/imprimerie' },
      { label: 'Développement Logiciel', path: '/services/developpement-logiciel' },
      { label: 'Câblage Réseau Structuré', path: '/services/cablage-reseau-informatique' },
      { label: 'Librairie & Papeterie', path: '/services/librairie-papeterie' },
    ],
  },
  {
    id: 'foot-nav',
    title: 'Navigation',
    sort_order: 2,
    is_visible: true,
    links: [
      { label: 'Accueil', path: '/' },
      { label: 'À propos de nous', path: '/a-propos' },
      { label: 'Nos réalisations', path: '/realisations' },
      { label: 'Catalogue produits', path: '/catalogue' },
      { label: 'Catalogue Librairie', path: LIBRAIRIE_CATALOGUE_URL },
      { label: 'Demander un devis', path: '/devis' },
      { label: 'Nous contacter', path: '/contact' },
    ],
  },
];
